SpinalHDL/VexRiscv

- src/test/cpp/regression/main.cpp
added missing using namespace std
i couldn't build the repo without this change
> updated main.cpp

- README.md
- src/test/scala/vexriscv/Play.scala
My earlier fix broke travis.
Tom
> Fix some missing Barriel -> barriel fixes

- README.md
* Fix a missing new line.
* Add link to the SBT source.
> Two minor fixes to README.md

- README.md
Signed-off-by: John McMaster <johndmcmaster@gmail.com>
> README.md: add missing newline

- README.md
Typos, languages, clarifications.
> Some minor updated to the manual

- src/main/scala/vexriscv/demo/GenMicroNoCsr.scala
- src/main/scala/vexriscv/plugin/BranchPlugin.scala
* Creates a configuration with removed WriteBack and Memory stage.
* Add warning when Memory stage is disabled and earlyBranch is false.
> GenMicro with warnings

- src/main/scala/vexriscv/plugin/DBusCachedPlugin.scala
- src/main/scala/vexriscv/plugin/DBusSimplePlugin.scala
- src/main/scala/vexriscv/plugin/MmuPlugin.scala
As discussed on Gitter, this gets Mmu working with a 2-stage pipeline
> Mmu 2 stage

- src/main/c/emulator/src/hal.c
This PR adds fixes to LiteX uart and timer "drivers".
I did my previous implementation in an emulator that failed to reproduce some behaviour. This version is tested in an actual FPGA.
> Fix handling LiteX uart and timer.

- README.md
While reading it, I took the time to make some corrections. Feel free to object to any of the modifications.
Btw, awesome work.
> Readme: fix spelling and made some clarifications

- src/main/scala/vexriscv/plugin/RegFilePlugin.scala
The RV32E extension removes registers x16-x31 from the ISA.  This
is useful when compiling with -mem2reg to save on BRAMs.  On iCE40
HX8K this option saves 1285 LC:s, which also improves the routing
situation, when using -mem2reg.
Note that the illegal instruction exception required by the RV32E
specification for accesses to registers x16-x31 is not implemented.
----
The missing exception could probably be implemented, but I'm afraid I'm not savvy enough in SpinalHDL to pull it off...  :sweat_smile:
> Add support for RV32E in RegFilePlugin

- src/main/scala/vexriscv/plugin/Misc.scala
Add support for the 8 C/FP L/S instructions. Enable a RV32IMAFDC buildroot to boot further than before, but not to reach login.
To be validated before merging...
> Attempt at supporting C (ompressed) and F/D (floating-point) together

- src/main/scala/vexriscv/demo/smp/VexRiscvSmpCluster.scala
- src/main/scala/vexriscv/demo/smp/VexRiscvSmpLitexCluster.scala
This enables changing the # of [ID] TLB entries from Litex.
Matching PR in Litex is https://github.com/enjoy-digital/litex/pull/906
> Make the [ID]TLB size configurable from Litex

- src/main/scala/vexriscv/plugin/DebugPlugin.scala
Add readback of the hardware breakpoint values.
A new parameter is added to the DebugPlugin to switch readback on and off.
> Update DebugPlugin.scala: Add optional readback of hardware breakpoint values

- src/main/scala/vexriscv/plugin/FormalPlugin.scala
This is just upstream change to support https://github.com/YosysHQ/riscv-formal/commit/891ea3694dfb4b47432f9fdaddff732005913283 that is now part of main riscv-formal release
> Update to latest risc-v-formal

- README.md
- doc/vjtag/README.md
- src/main/scala/vexriscv/plugin/DebugPlugin.scala
Also added some documentation of the process
> Add ability to debug over Intel Virtual JTAG

- src/main/scala/vexriscv/plugin/MmuPlugin.scala
Vex only implements a 32-bit PA which does not take advantage of the potetnial 32-bit space in Sv32 mode. Very reasonably, Vex simply discards the top two unused bits.
However, the spec does require that the register occupy all 22 bits and it is possible for the OS to use the extra bits up top for some bookkeeping purpose. This commit proposes to expand the register to occupy the full 22 bits in case an OS is written to utilize the full width of the register as written in the spec.
I have tested the commit and confirmed it does not interfere with proper operation in Xous. I think it should also not cause any issues for Linux either, since it should just enable storing of an extra two bits an the top of the PPN that would normally be reported as zero.
> Expand SATP register to 22 bits per spec

- src/test/cpp/custom/atomic/src/crt.S
Fix incorrect comment in custom/atomic/src/crt.S
> Fix incorrect comment

- src/main/scala/vexriscv/plugin/DBusSimplePlugin.scala
> Exposed write mask on default iBus

- README.md
- src/main/scala/vexriscv/plugin/EmbeddedRiscvJtag.scala
This change allows tunneling JTAG (e.g. with Xilinx BSCANE2) to the VexRiscv EmbeddedRiscvJtag plugin. The plugin required another case to handle tunneling without creating a TAP.
This change also adds a section to README.md that shows how to use it with Xilinx BSCANE2.
I successfully tested it using a "smallest" configuration on a XC7A200T-FBG676 with a Digilent HS3 adapter and upstream riscv-openocd.
> Tunneled EmbeddedRiscvJtag without TAP

- build.sbt
Bump SpinalHDL to 1.10.2a and Scala to 2.12.
> build.sbt: Bump SpinalHDL and Scala version

- src/main/scala/vexriscv/plugin/DBusSimplePlugin.scala
> DBusSimplePlugin: don't force SEL to 1111 on read.

- src/main/scala/vexriscv/ip/DataCache.scala
- src/main/scala/vexriscv/ip/InstructionCache.scala
- src/main/scala/vexriscv/plugin/DBusSimplePlugin.scala
- src/main/scala/vexriscv/plugin/IBusSimplePlugin.scala
Add the wishbone granularity attribute to the conversion functions for iBus / dBus
> Add address granularity for wishbone
