src/main/scala/vexriscv/demo/Murax.scala
Changes GPIO width from hard coded to gpioWidth so it can be adjusted through instantiation parameter.
Adds explicit type to apbDecoder.slave to suppress IDE errors in IntelliJ.
=> Minor fixes to Murax.scala

.gitignore, src/main/scala/vexriscv/plugin/DBusSimplePlugin.scala, src/main/scala/vexriscv/plugin/IBusSimplePlugin.scala
This is a trivial patch, but the lack of this function while similar ones were present for other busses, made me assume that .toPipelinedMemoryBus() didn't exist...
Tom
=> Add getPipelinedMemoryBusConfig()

src/main/scala/vexriscv/plugin/Mul16Plugin.scala
This adds yet another multiplication plugin variant. The goal here was to only use 16-bit multiplications to implement a 32x32bit multiplier, with the intention to utilize 16-bit DSPs of some FPGAs. I've confirmed that the Icestorm (Yosys+Nextpnr) toolchain will synthesize and place this into the DSP cells of a iCE40 UltraPlus 5K FPGA. Yosys requires the `-dsp` flag for the `synth_ice40` command and will then correctly detect the multiplication operator. 
I originally developed this in the context of [https://github.com/mupq/pqriscv-vexriscv](https://github.com/mupq/pqriscv-vexriscv), but I think others might find this interesting. And I also hope to get some feedback on it.
=> Multiplication Plugin using 16-bit DSPs

scripts/Murax/arty_a7/make_vivado_project, scripts/Murax/arty_a7/soc_mmi.tcl
My Vivado version (2018.3) infers `RAMB18E1`s instead of `RAMB36E1`s, which is probably more area-efficient (or maybe it's the same after optimization). But this breaks a TCL script that assumes the second case; after this patch, it should be compatible with both.
=> Murax on arty_a7: fix inferred memory type

src/main/scala/vexriscv/demo/Murax.scala, src/main/scala/vexriscv/demo/MuraxUtiles.scala, src/main/scala/vexriscv/plugin/DBusSimplePlugin.scala, src/main/scala/vexriscv/plugin/IBusSimplePlugin.scala
I have tested this on an iCE40 HX8K breakout board.
Big-endian support for the toolchain can be found [here](https://github.com/zeldin/binutils-gdb/tree/riscv-bigendian) and [here](https://github.com/zeldin/gcc/tree/riscv-bigendian).
Interrestingly enough, `nextpnr-ice40` reports a higher fMax (73.09 MHz w/o RVC, 66.64 MHz with RVC) for big endian Murax than for little endian (72.35 MHz w/o RVC, 62.09 MHz with RVC), although I don't know why big endian would be faster...
=> Add support for big endian byte ordering

src/main/scala/vexriscv/plugin/IBusSimplePlugin.scala
Between draft-20181101-ebe1ca4 and draft-20190622-6993896 of the
RISC-V Instruction Set Manual, the wording was changed from requiring
"natural endianness" of instruction parcels to require them to be
little endian.
Update the big endian instruction pipe to reflect the newer requirement.
Updated toolchains can be found here:
https://github.com/zeldin/riscv-binutils-gdb/commits/big-endian
https://github.com/zeldin/riscv-gcc/commits/big-endian
=> Update big endian instruction encoding

src/main/scala/vexriscv/Services.scala, src/main/scala/vexriscv/ip/DataCache.scala, src/main/scala/vexriscv/ip/InstructionCache.scala, src/main/scala/vexriscv/plugin/DBusCachedPlugin.scala, src/main/scala/vexriscv/plugin/MmuPlugin.scala, src/main/scala/vexriscv/plugin/PmpPlugin.scala, src/main/scala/vexriscv/plugin/StaticMemoryTranslatorPlugin.scala
VexRiscv was originally implemented before the introduction of PMP, so the `MemoryTranslatorRsp` class has no way of differentiating between faults resulting from the MMU and faults resulting from PMP. This PR adds a new flag called `isPaging` to indicate whether the `allowRead`, `allowWrite` and `allowExecute` flags refer to MMU or PMP permissions. This flag is handled by the data and instruction bus plugins to determine whether to throw access faults or page faults.
This fixes a bug where the PMP plugin throws page faults (12, 13, 15) instead of access faults (1, 5, 7) as the specification expects.
=> Distinguish between page faults from MMU and access faults from PMP

src/main/scala/vexriscv/Riscv.scala, src/main/scala/vexriscv/plugin/CfuPlugin.scala
Define "h" [31:24] and "h_sext" (sign extended "h"), and use it as the IMMED field in the CFU plugin.
Also cherry-pick a fix from dev branch regarding variable names.
=> CFU spec -- update immed data sent in place of RS2.

src/test/cpp/regression/main.cpp
I has getting some 
```
../main.cpp:1198:24: warning: & has lower precedence than !=; != will be evaluated first [-Wparentheses]
if(address & (size-1) != 0)
^~~~~~~~~~~~~~~
```
when building, so i fixed the lines where there was a missing parenthesis. 
Remarks welcome
=> fixed priority of == & != as seemed logical 

src/main/scala/vexriscv/demo/Linux.scala
Correct "machime" to "machine".
=> Fix typo in Linux.scala

src/main/scala/vexriscv/plugin/CsrPlugin.scala
Both counters are initialized with "randBoot()". This is fine for FPGA
designs because the registers can be loaded with default values but
ASIC designs require to load the value during a reset.
Since both counters require to start at 0 (read-only CSR registers),
change both registers from "randBoot()" to "init(0)".
Error:
reg        [63:0]   CsrPlugin_mcycle = 64'b0000000...00000000000;
|
Warning : Ignoring unsynthesizable construct. [VLOGPT-37]
Signed-off-by: Daniel Schultz <d.schultz@phytec.de>
=> plugin: CsrPlugin: Init cycle and instret registers

src/main/scala/vexriscv/plugin/DBusSimplePlugin.scala
This assert triggered sometimes at the beginning of a simulation.
Since it's not really needed anymore, we can remove it.
Signed-off-by: Daniel Schultz <daniel.schultz@aesc-silicon.de>
=> plugin: DBusSimplePlugin: Remove assert

src/main/scala/vexriscv/demo/GenCustomSimdAdd.scala, src/test/cpp/custom/simd_add/src/ld
With the old reset vector half of the tests fail since
they expect the CPU to start at 0x80000000.
=> Fix reset vector of GenCustomSimdAdd

src/main/scala/vexriscv/plugin/DBusCachedPlugin.scala, src/main/scala/vexriscv/plugin/IBusCachedPlugin.scala
Both registers were initialized with unsigned integers without a value.
This triggered:
[error] Exception in thread "main" spinal.core.SpinalExit:
[error]  Can't resolve the literal value of (..._rspCounter :  UInt[32 bits])
Signed-off-by: Daniel Schultz <dnltz@aesc-silicon.de>
=> plugin: caches: Fix "Can't resolve the literal value of"

README.md
When I study about Briey Soc, I found there is a invalid hyperlink.
And I search the information from the official website
=> Fix invalid hyperlink

src/main/scala/vexriscv/plugin/CsrPlugin.scala, src/main/scala/vexriscv/plugin/MmuPlugin.scala
This PR adds a flag that allows the configuration to expose the SATP value for external inspection.
The primary motivation for this is to allow hardware to determine, when a system is running in virtual memory mode, if a given process is allowed to access sensitive data. The operative theory is that the SATP is intimately linked to the virtual process that is running, and by exposing this data outside the core we can make decisions about the state of the machine easily.
Hopefully the flag is coded in a way that users which do not care about this feature are not impacted by it. Let me know if you would prefer it coded in a different way for minimal impact on most users who do not share such security concerns.
=> Expose satp

src/main/scala/vexriscv/Services.scala, src/main/scala/vexriscv/VexRiscv.scala, src/main/scala/vexriscv/plugin/Fetcher.scala, src/main/scala/vexriscv/plugin/FormalPlugin.scala
Previously, FORMAL_MODE would simply be hard-coded to "11", indicating machine mode. However, that's not necessarily true when using the CsrPlugin, which allows to switch the hart into either User or optional Supervisor mode. Hence we create a FORMAL_MODE insert in the fetch-phase (which is generally when the MPP register can take effect) and generate `rvfi_mode` based on that insert.
=> Fetcher: insert FORMAL_MODE encoded from privilegeService

src/main/scala/vexriscv/plugin/CsrPlugin.scala
The `FormalPlugin` requires a `FORMAL_HALT` insert to indicate whether the CPU will halt after retiring the current instruction. As this insert is provided only by the `HaltOnExceptionPlugin`, and the `CsrPlugin` also provides a conflicting `ExceptionService`, currently the `FormalPlugin` can't be used with the `CsrPlugin`. As there is no way to halt the CPU with the `CsrPlugin`, simply deassert `FORMAL_HALT`.
=> CsrPlugin: insert FORMAL_HALT := False

project/plugins.sbt
The plugin is not used in the VexRiscV build and causes issues for users since repo.scala-sbt.org seems to be down/sunset/?.
See also https://github.com/sbt/sbt/issues/7202
Updating the dependency would also have been an option, but since it's not used removal is easier.
=> Remove sbt-assembly dependency

src/main/scala/vexriscv/plugin/DBusSimplePlugin.scala
Motivated by https://github.com/SpinalHDL/VexRiscv/issues/347#issuecomment-1587520015.
Adds a function called `cmdHalfPipe` to `DBusSimpleBus` which allows for a simple `halfPipe()` insertion on the `cmd` Stream in order to break combinatorial loops(when necessary).
Tested manually on board with Briey that used AhbLite3 interconnect(which forces the use of DBusSimplePlugin since Cached plugin does not have the `toAhbLite3Master()` function)
=> Add cmd halfPipe function to DBusSimpleBus

src/main/scala/vexriscv/plugin/PmpPluginOld.scala
Because
- pmpaddrX registers are defined to encode the address' [XLEN + 2 downto 2] bits,
- the length of a NAPOT region is defined through the most significant 0 bit in a pmpaddrX register (which in the case of ~0 is the 33rd non-existant "virtual" bit),
- and the VexRiscv PmpOld plugin represents the addresses covered by a region as [start; end) (bounded inclusively below and exclusively above),
the start and end address registers need to be XLEN + 4 bit wide to avoid overflows.
If such an overflow occurs, it may be that the region does not cover any address, an issue uncovered in the Tock LiteX + VexRiscv CI during a PMP infrastructure redesign in the Tock OS [1].
This commit has been tested on Tock's redesigned PMP infrastructure, and by inspecting all of the intermediate signals in …
=> PmpPluginOld: fix NAPOT address calculation overflow issue

src/test/cpp/common/jtag.h
The call to `bind()` can actually resolve to `std::bind()` instead of libc's `bind()`.
This fix ensures that we're definitely always calling the correct `bind()`.
Took me way too long to hunt this one down...
This happened with `clang++ 16.0.6`.
=> Fix ambiguous function call to bind()

.gitignore, README.md, build.sc
Hi, sbt is a very heavy tool to build scala files, instead, mill is very simple and benefit to use in offline environment.
So i add whole mill compile and test scripts.
=> Add mill to compile and test VexRiscv

src/main/scala/vexriscv/VexRiscv.scala, src/main/scala/vexriscv/demo/smp/VexRiscvSmpCluster.scala
When generating SMP configuration with supervisor disable, the compiler stucks at waiting for the signal from
`externalSupervisorInterrupt`, which is generated conditionally based on `withSupervisor` in CsrPlugin.
=> Fix SMP compile-time error when disabling supervisor option

src/main/scala/vexriscv/ip/DataCache.scala, src/main/scala/vexriscv/ip/InstructionCache.scala, src/main/scala/vexriscv/plugin/DBusSimplePlugin.scala, src/main/scala/vexriscv/plugin/IBusSimplePlugin.scala
This PR implements handling `ERR` in `toWishbone`. 
Note that the following may look strange:
```scala
cmdBridge.ready := cmdBridge.valid && (bus.ACK || bus.ERR)
```
But this is imposed by the Wishbone spec:
> *Rule 3.45*
> If a SLAVE supports the `[ERR_O]` or `[RTY_O]` signals, then the SLAVE MUST NOT assert more than one of the following signals at any time: `[ACK_O]`, `[ERR_O]` or `[RTY_O]`.
----------
Questions for reviewers:
* Is there an example regression test for, say, AXI error handling I could use as a base for a Wishbone test?
* Where can I add a changelog entry (if applicable)?
=> Handle `ERR` in `toWishbone`

README.md, doc/gcdPeripheral/src/main/scala/vexriscv/demo/Murax.scala, src/main/scala/vexriscv/demo/Murax.scala, src/main/scala/vexriscv/ip/fpu/FpuCore.scala, src/main/scala/vexriscv/plugin/AesPlugin.scala, src/test/scala/vexriscv/DhrystoneBench.scala
SI units are case sensitive and analog engineers are very sensitive to this :)
It seems that the Dhrystone benchmark is done with .asm files, perhaps generated from [here](https://github.com/Keith-S-Thompson/dhrystone), where [Hz](https://en.wikipedia.org/wiki/Hertz) is wrongly spelled "hz".
This PR fix this in the README, the scala code that seems to generate the README but not the .asm files.
Ideally a fix in the upstream C code repos would also be  needed, but IMHO it's not a good idea, because it would break too many tests like this one.
Note that I didn't test the fix in the scala file because I don't have a running VexRiscv setup.
=> Fix Mhz -> MHz in README, comments and Dhrystone benchmark output

src/test/cpp/briey/makefile, src/test/cpp/murax/makefile, src/test/cpp/regression/makefile
fixes https://github.com/SpinalHDL/VexRiscv/issues/431
=> Verilator requires at least c++14

src/main/scala/vexriscv/plugin/IBusSimplePlugin.scala
So I am using https://github.com/efabless/openlane2/ to synthesize VexRiscv for SKY130, and I am facing synthesis issues due to an undriven pin:
Verilator Linting:
```
%Warning-UNDRIVEN: VexRiscv.v:780:23: Signal is not driven: 'IBusSimplePlugin_rspJoin_fetchRsp_isRvc'
: ... note: In instance 'top.VexRiscv_inst'
780 |   wire                IBusSimplePlugin_rspJoin_fetchRsp_isRvc;
|                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
Resulting error: `ABC: Error: The network is combinational.`
Thanks to verilator's linting, I was able to pin down the signal that is missing an assignment.
However, since I am not familiar with code base, my proposed "fix" might not be semantically correct, but at least fixes the synthesis issues.
For the sake of completeness, this is the …
=> Fix undriven signal

doc/nativeJtag/README.md, src/main/scala/vexriscv/demo/Murax.scala
I will use the native Jtag on AMD FPGAs often, so I created a Murax config according to the docs in:
https://github.com/SpinalHDL/VexRiscv/tree/master/doc/nativeJtag
It was my first experience with Scala. I would be glad to hear your feedback on whether my approach with `ifGen` is plausible. I had doubts about whether I should create an independent `class` or not.
=> add Murax config with native jtag based on the docs

build.sbt, build.sc
Codebase requires int support in isPow2, the latest version of spinal has this support.
=> Bump to Spinal version 1.12.0
